### ISSUE TITLE
Is still working?

### ISSUE THREAD

**Issue by qwerty32123** [Ayeven/bdocodexscrap#1]
Im searching something to scrape all the recipes and store in my raspberry

also how it works

**Comment by Ayeven** [comment]
I didnt include scrapping the recipe. Later this afternoon will upload file on scrapping it. Edit : working copy on replit https://repl.it/@Ayeven/bdocodexscrap#wip/recipes_us.js
You will need to modifiy to your need. And the recipe scrapping is in wip folder.

`[
  {
    lvl: '技能等級: 初級 Lv. 6',
    category: '料理',
    name: '五穀雞肉粥',
    mats1: '剁碎的鳥肉',
    qtty1: '2',
    mats2: '料理用飲用水',
    qtty2: '2',
    mats3: '谷物',
    qtty3: '3'
  }
]`
example of the result

**Comment by qwerty32123** [comment]
Im getting 

` node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/runner/JEHlfPJqCof/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
exit status 1



`


on repl.it

**Comment by Ayeven** [comment]
because I didn't make `index.js`, If you want to test it out, do `cd ./wip` then `node recipes_us` on the `shell` windows. You should learn the basic of JS if you really wish to use this
